/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Airline1;

import javax.swing.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
/**
 *
 * @author MeherunNesaShraboni
 */
public class airline_review extends JFrame {

    public int from;
    public int to;

    /**
     * Creates new form airline_review
     */
    public airline_review() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        seePassengerNumber = new javax.swing.JButton();
        To = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("From Airport");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 270, 110, 20);
        jPanel1.add(From);
        From.setBounds(360, 270, 160, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("To Airport");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 310, 80, 22);

        seePassengerNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seePassengerNumber.setText("Click To see Passenger");
        seePassengerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassengerNumberActionPerformed(evt);
            }
        });
        jPanel1.add(seePassengerNumber);
        seePassengerNumber.setBounds(370, 380, 240, 31);
        jPanel1.add(To);
        To.setBounds(360, 310, 160, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeherunNesaShraboni\\Downloads\\43222337274_07356f9f24_o.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seePassengerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePassengerNumberActionPerformed
        // TODO add your handling code here:

        //from=From.getText();
        //to=To.getText();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy   HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String showDateAndTime=new String(dtf.format(now));
        System.out.println(showDateAndTime);
        
        from = Integer.parseInt(From.getText());
        //From.setText(Integer.toString(a));
        to = Integer.parseInt(To.getText());
        //To.setText(Integer.toString(a));
        int i = DB.datch_2(from, to, showDateAndTime);
        if (i > 0) {
            JOptionPane.showMessageDialog(airline_review.this, "Your flight route is ready.");
        } else {
            JOptionPane.showMessageDialog(airline_review.this, "Sorry! Unable to find path.......");
        }
        System.out.println(from + " " + to);
        dispose();
        Max_Passenger ai = new Max_Passenger(from, to);
        ai.setLocationRelativeTo(null);
        ai.setVisible(true);

    }//GEN-LAST:event_seePassengerNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(airline_review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(airline_review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(airline_review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(airline_review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new airline_review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField From;
    private javax.swing.JTextField To;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton seePassengerNumber;
    // End of variables declaration//GEN-END:variables
}
