/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Airline1;

/**
 *
 * @author MeherunNesaShraboni
 */
public class Graph_input extends javax.swing.JFrame {

    /**
     * Creates new form Graph_input
     */
    public Graph_input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        onetotwotf = new javax.swing.JTextField();
        onetothreetf = new javax.swing.JTextField();
        twotothreetf = new javax.swing.JTextField();
        twotofourtf = new javax.swing.JTextField();
        threetotwotf = new javax.swing.JTextField();
        threetofivetf = new javax.swing.JTextField();
        fourtothreetf = new javax.swing.JTextField();
        fourtosixtf = new javax.swing.JTextField();
        fivetofourtf = new javax.swing.JTextField();
        fivetosixtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("This Page is for Editing Passenger Number");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 60, 470, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Airport 1 to 2");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 230, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Airport 1 to 3");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 280, 107, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Airport 2 to 3");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 320, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Airport 2 to 4");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 370, 110, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Airport 3 to 2");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 410, 107, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Airport 3 to 5");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(290, 230, 120, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Airport 4 to 3");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(290, 280, 107, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Airport 4 to 6");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(290, 320, 107, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Airport 5 to 4");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(290, 370, 107, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Airport 5 to 6");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(290, 410, 107, 22);
        jPanel2.add(onetotwotf);
        onetotwotf.setBounds(180, 230, 80, 26);
        jPanel2.add(onetothreetf);
        onetothreetf.setBounds(180, 280, 80, 26);
        jPanel2.add(twotothreetf);
        twotothreetf.setBounds(180, 320, 80, 26);
        jPanel2.add(twotofourtf);
        twotofourtf.setBounds(180, 370, 80, 26);
        jPanel2.add(threetotwotf);
        threetotwotf.setBounds(180, 410, 80, 26);
        jPanel2.add(threetofivetf);
        threetofivetf.setBounds(420, 230, 80, 26);
        jPanel2.add(fourtothreetf);
        fourtothreetf.setBounds(420, 280, 80, 26);
        jPanel2.add(fourtosixtf);
        fourtosixtf.setBounds(420, 330, 80, 26);
        jPanel2.add(fivetofourtf);
        fivetofourtf.setBounds(420, 370, 80, 26);
        jPanel2.add(fivetosixtf);
        fivetosixtf.setBounds(420, 410, 80, 26);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Click Here To Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(670, 440, 175, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(860, 440, 93, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeherunNesaShraboni\\Downloads\\43222337274_07356f9f24_o.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

int one=Integer.parseInt(onetotwotf.getText());
int two=Integer.parseInt(onetothreetf.getText());
int three=Integer.parseInt(twotothreetf.getText());
int four=Integer.parseInt(twotofourtf.getText());
int five=Integer.parseInt(threetotwotf.getText());
int six=Integer.parseInt(threetofivetf.getText());
int seven=Integer.parseInt(fourtothreetf.getText());
int eight=Integer.parseInt(fourtosixtf.getText());
int nine=Integer.parseInt(fivetofourtf.getText());
int ten=Integer.parseInt(fivetosixtf.getText());
/*
onetotwotf.setText(Integer.toString(one));
onetothreetf.setText(Integer.toString(one));
twotothreetf.setText(Integer.toString(one));
twotofourtf.setText(Integer.toString(one));
threetotwotf.setText(Integer.toString(one));
threetofivetf.setText(Integer.toString(one));
fourtothreetf.setText(Integer.toString(one));
fourtosixtf.setText(Integer.toString(one));
fivetofourtf.setText(Integer.toString(one));
fivetosixtf.setText(Integer.toString(one));
*/

DB.graph_input(one,two,three,four,five,six,seven,eight,nine,ten);


 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         dispose();
        AdminControlPanel ai=new AdminControlPanel();
        ai.setLocationRelativeTo(null);
        ai.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph_input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fivetofourtf;
    private javax.swing.JTextField fivetosixtf;
    private javax.swing.JTextField fourtosixtf;
    private javax.swing.JTextField fourtothreetf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField onetothreetf;
    private javax.swing.JTextField onetotwotf;
    private javax.swing.JTextField threetofivetf;
    private javax.swing.JTextField threetotwotf;
    private javax.swing.JTextField twotofourtf;
    private javax.swing.JTextField twotothreetf;
    // End of variables declaration//GEN-END:variables
}
